name: Update Money Rates Page

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate updated rates.html
        run: python generate_html.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add rates.html
          git commit -m "Update rates.html [CI skip]" || echo "No changes"
          git push
