name: Update Money Rates Page

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate updated rates.html
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python generate_html.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add rates.html
          git commit -m "Update rates.html [ci skip]" || echo "No changes to commit"
          git push
